### PR TITLE
migrate from TravisCI to GitHub Actions

### PR DESCRIPTION
**Pull request by tracfren**
*Description of changes:*

Builds are broken on PRs. Migrating to GitHub actions in hopes it will fix it.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by NorbertNader** [comment]
Looks like there are some build failures.

**Comment by tracfren** [comment]
@NorbertNader It looks like it wasn't handling `npm ci` well. Updated to `npm i` and build succeeded!

**Review by NorbertNader — APPROVED** [review]

**Comment by tracfren** [comment]
To merge this PR, I plan to bypass the Travis CI check as it is being removed in this PR.

**Comment by tracfren** [comment]
NVM just disabled that check. No bypassing required.

**Pull request merged**
