### PR TITLE
Add capability for multiple custom connectors to be connected to edges

### PR DESCRIPTION
**Pull request by ktsao565**
This is an initial PR to get some eyes on the overall approach. Additional unit tests and integ tests are in progress, but I wanted to initiate the initial review on the high level changes. 

*Issue #, if available:* https://github.com/awslabs/diagram-maker/issues/67

*Description of changes:* 
- Add capability for edges to connect to individual custom connectors
- Allow consumer to configure the position of custom connectors

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Review by NorbertNader — APPROVED** [review]

**Review by sameergoyal — COMMENTED** [review]
I'm no longer at Amazon, but thought I would take a look & provide feedback since this is an important feature to be added to Diagram Maker. Feel free to act on the parts of my feedback that make sense and ignore the rest.

Great job on the PR and very well executed change. I've added some minor feedback around avoiding conditionals where they seem unnecessary.

One more general piece of feedback would be to add:
1. More unit tests
2. Update the demo & documentation
3. Add integration tests.

Usually 2 & 3 go hand in hand since we use our demo pages as integ test environment so hopefully you can save some time there.

**Comment by sameergoyal** [comment]
Just checking if there are plans to address the comments and merge this one in?

**Comment by matr369** [comment]
any updates?

**Review by tracy-french — APPROVED** [review]

**Comment by tracy-french** [comment]
@matr369 Change has been merged.

**Pull request merged**
